version: "3.10"
services:
  db:
    container_name: postgres_container
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  flask_app:
    container_name: flask_app_container
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_URL: postgresql://root:root@db:5432/postgres
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
    volumes:
      - .:/app

volumes:
  postgres_data: {}
